// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././platypus.proto
package com.platypus.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class RegionMission extends Message {

  public static final List<Vector3> DEFAULT_BOUNDS = Collections.emptyList();
  public static final String DEFAULT_TYPE = "";

  @ProtoField(tag = 1, label = REPEATED)
  public final List<Vector3> bounds;

  @ProtoField(tag = 2, type = STRING)
  public final String type;

  private RegionMission(Builder builder) {
    super(builder);
    this.bounds = immutableCopyOf(builder.bounds);
    this.type = builder.type;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RegionMission)) return false;
    RegionMission o = (RegionMission) other;
    return equals(bounds, o.bounds)
        && equals(type, o.type);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = bounds != null ? bounds.hashCode() : 0;
      result = result * 37 + (type != null ? type.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RegionMission> {

    public List<Vector3> bounds;
    public String type;

    public Builder() {
    }

    public Builder(RegionMission message) {
      super(message);
      if (message == null) return;
      this.bounds = copyOf(message.bounds);
      this.type = message.type;
    }

    public Builder bounds(List<Vector3> bounds) {
      this.bounds = bounds;
      return this;
    }

    public Builder type(String type) {
      this.type = type;
      return this;
    }

    @Override
    public RegionMission build() {
      return new RegionMission(this);
    }
  }
}
