// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././platypus.proto
package com.platypus.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Label.REQUIRED;

public final class Velocity extends Message {

  @ProtoField(tag = 1, label = REQUIRED)
  public final Vector3 linear;

  @ProtoField(tag = 2, label = REQUIRED)
  public final Vector3 angular;

  private Velocity(Builder builder) {
    super(builder);
    this.linear = builder.linear;
    this.angular = builder.angular;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Velocity)) return false;
    Velocity o = (Velocity) other;
    return equals(linear, o.linear)
        && equals(angular, o.angular);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = linear != null ? linear.hashCode() : 0;
      result = result * 37 + (angular != null ? angular.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Velocity> {

    public Vector3 linear;
    public Vector3 angular;

    public Builder() {
    }

    public Builder(Velocity message) {
      super(message);
      if (message == null) return;
      this.linear = message.linear;
      this.angular = message.angular;
    }

    public Builder linear(Vector3 linear) {
      this.linear = linear;
      return this;
    }

    public Builder angular(Vector3 angular) {
      this.angular = angular;
      return this;
    }

    @Override
    public Velocity build() {
      checkRequiredFields();
      return new Velocity(this);
    }
  }
}
