// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ././platypus.proto
package com.platypus.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class WaypointMission extends Message {

  public static final List<Vector3> DEFAULT_WAYPOINTS = Collections.emptyList();
  public static final String DEFAULT_TYPE = "";

  @ProtoField(tag = 1, label = REPEATED)
  public final List<Vector3> waypoints;

  @ProtoField(tag = 2, type = STRING)
  public final String type;

  private WaypointMission(Builder builder) {
    super(builder);
    this.waypoints = immutableCopyOf(builder.waypoints);
    this.type = builder.type;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof WaypointMission)) return false;
    WaypointMission o = (WaypointMission) other;
    return equals(waypoints, o.waypoints)
        && equals(type, o.type);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = waypoints != null ? waypoints.hashCode() : 0;
      result = result * 37 + (type != null ? type.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<WaypointMission> {

    public List<Vector3> waypoints;
    public String type;

    public Builder() {
    }

    public Builder(WaypointMission message) {
      super(message);
      if (message == null) return;
      this.waypoints = copyOf(message.waypoints);
      this.type = message.type;
    }

    public Builder waypoints(List<Vector3> waypoints) {
      this.waypoints = waypoints;
      return this;
    }

    public Builder type(String type) {
      this.type = type;
      return this;
    }

    @Override
    public WaypointMission build() {
      return new WaypointMission(this);
    }
  }
}
